# Generated by Django 3.2.7 on 2021-10-19 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0004_helpdeskmessage_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskmessage',
            name='to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_helpdesk_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
