# Generated by Django 3.2.7 on 2021-10-14 15:13

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=services.models.services_img_path),
        ),
    ]
