# Generated by Django 3.2.8 on 2021-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='blacklist_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
