# Generated by Django 3.2.7 on 2021-10-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_session_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='provided',
            field=models.BooleanField(default=False),
        ),
    ]
