# Generated by Django 3.2.7 on 2021-10-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20211015_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cancellation_reason',
            field=models.TextField(default=''),
        ),
    ]
