# Generated by Django 3.2.7 on 2021-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20211015_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='was_rated',
            field=models.BooleanField(default=False),
        ),
    ]
