# Generated by Django 3.2.7 on 2021-10-13 12:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=2), size=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Специальный график',
                'verbose_name_plural': 'Исключения из графиков',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('schedule_days', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), size=None)),
                ('schedule_time', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['-start'],
                'unique_together': {('user', 'start')},
            },
        ),
    ]
