# Generated by Django 3.2.7 on 2021-10-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialschedule',
            name='times',
        ),
    ]
