# Generated by Django 3.2.7 on 2021-10-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedules', '0002_remove_specialschedule_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialschedule',
            name='times',
            field=models.JSONField(default=None, null=True),
        ),
    ]
